// <auto-generated />
namespace DomainDrivenDesignArchitecture.Repository.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Task_Simple_01_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Task_Simple_01_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201804092053544_Task_Simple_01_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
